language: c

branches:
  only:
  - main

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
            - valgrind
            - libpcre2-dev
            - libuv1-dev
            - libyajl-dev
      env:
         - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - git clone https://github.com/transceptor-technology/libcleri.git
  - cd ./libcleri/Release/
  - make
  - sudo make install
  - cd ../../Release/
  - sudo rm /usr/bin/gcc
  - sudo ln -s /usr/bin/gcc-9 /usr/bin/gcc
  - gcc --version

script:
  - make test
  - CFLAGS="-Werror -Winline -std=gnu11" make
