name: Deploy

on:
  workflow_dispatch:
  push:
    tags:
    - "v*-*" # v1.2.3-alpha0 etc.

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        username: rickmoonen
        password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image (minimal)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        file: docker/Dockerfile
        tags: rickmoonen/thingsdb-test:platform
        platforms: linux/amd64
